# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.

# Default server configuration

events { worker_connections 1024; }

http {
    include         /etc/nginx/mime.types;
    include         /etc/nginx/conf.d/*.conf;
    default_type    application/octet-stream;

    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

server {
	listen 80;
	listen [::]:80;
	server_name clilinux.com www.clilinux.com;
	return 301 https://$host$request_uri;
    }

server {
	listen 80;
	listen [::]:80;
	server_name remark42.clilinux.com;
	return 301 https://$host$request_uri;
    }

server {
	listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
	server_name clilinux.com www.clilinux.com;

	ssl    on;
	ssl_certificate        /etc/nginx/certs/wildcard/fullchain.pem;
	ssl_certificate_key    /etc/nginx/certs/wildcard/privkey.pem;

    gzip off;

	root /usr/share/nginx/html;

	index index.html;

    location ~ \.css {
    add_header  Content-Type    text/css;
    }

	location / {
		try_files $uri $uri/ =404;
	    }
    }

server {
    listen 443 ssl;
    listen [::]:443 ssl ipv6only=on;
    server_name remark42.clilinux.com;

    ssl    on;
    ssl_certificate /etc/nginx/certs/wildcard/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/wildcard/privkey.pem;

    gzip on;
    gzip_types text/plain application/json text/css application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;
    gzip_min_length 1024;
    gzip_proxied any;


    location ~ /\.git {
        deny all;
    }

    location /index.html {
         proxy_redirect          off;
         proxy_set_header        X-Real-IP $remote_addr;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        Host $http_host;
         proxy_pass              http://remark42:8080/web/index.html;
     }

    location / {
         proxy_redirect          off;
         proxy_set_header        X-Real-IP $remote_addr;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        Host $http_host;
         proxy_pass              http://remark42:8080/;
    }

    access_log   /var/log/nginx/remark42.log;
    }
}
